#Stores information on unclaimed books
books:
  player_name:
    book1:
      title: Set Stone
      commands:
        - //hpos1
        - //hpos2
        - //set 1
      version: 1.7
    book2:
      title: Kick player
      commands:
        - /kick %player%
      version: 1.8
permissions:
  gamemode:
    - bukkit.command.gamemode
    - essentials.gamemode