name: OneTimeCode
main: com.mctoybox.onetimecode.MainClass
version: 1.3
author: Sir_Speshkitty
softdepend: [WorldEdit]
commands:
  otc:
    default: true
    description: All OneTimeCode commands
    usage: |
      /<command>
      /<command> <player> <commanddata>
permissions:
  otc.use:
    default: true
    description: Allows using OTC books
  otc.create:
    default: op
    description: Allows creating OTC books