name: OneTimeCode
main: com.mctoybox.onetimecode.MainClass
version: 1.7
author: Sir_Speshkitty
depend: [Vault]
softdepend: [WorldEdit]
commands:
  otc:
    description: Using OTC books
    permission: otc.use
    usage: /<command>
  createotc:
    description: Creating OTC books
    permission: otc.create
    usage: /<command> <player> <commanddata>
  claimotc:
    description: Used for claiming OTC books
    permission: otc.use
    usage: /<command>
permissions:
  otc.use:
    default: true
    description: Allows using OTC books
  otc.create:
    default: op
    description: Allows creating OTC books